name: Deploy to VPS

on:
  push:
    branches: [ develop ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.VPS_SSH_KEY }}
        known_hosts: ${{ secrets.VPS_KNOWN_HOSTS }} # Opcional
        if_key_exists: replace

    - name: Adding Known Hosts
      run: ssh-keyscan -p ${{ secrets.VPS_PORT }} ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy with rsync
      run: |
        rsync -avz -e "ssh -p ${{ secrets.VPS_PORT }}" --exclude='.git' --exclude='venv' --exclude='node_modules' ./ ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:/home/${{ secrets.VPS_USER }}/finaBotTelegram

    - name: Restart Docker Services
      run: |
        ssh -p ${{ secrets.VPS_PORT }} ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
          cd /home/${{ secrets.VPS_USER }}/finaBotTelegram
          docker-compose down --remove-orphans
          docker-compose build
          docker-compose up -d
          docker-compose ps
        EOF
